% Smart Hearing Aid - Final Year Project
% Author: Sergio Gosalvez
% Imperial College London 2022

% Add different part folders to path

addpath('Recordings/');
addpath('Functions/');
addpath('App/');


% Set deafault graphic settings

set(groot,  'DefaultLineLineWidth', 4, ...
            'DefaultTextInterpreter', 'LaTeX', ...
            'DefaultAxesFontSize', 25, ...
            'DefaultLegendInterpreter', 'LaTeX', ...
            'DefaultAxesLineWidth', 1.5, ...
            'DefaultStemLineWidth', 2.5, ...
            'DefaultAxesFontSize',25,...
            'DefaultFigureColor','w');
